# Generated by Django 5.2.1 on 2025-05-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Characters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('true_name', models.CharField(blank=True, max_length=100)),
                ('age', models.CharField(max_length=50)),
                ('vital_status', models.CharField(max_length=50)),
                ('rank', models.CharField(max_length=100)),
                ('class_name', models.CharField(blank=True, max_length=100)),
                ('aspect', models.CharField(max_length=100)),
                ('flaw', models.CharField(blank=True, max_length=100)),
                ('image', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
